// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/list-recent-voice-logs.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/tools/_sb.ts
import { createClient } from "npm:@supabase/supabase-js@^2.76.1";
function sb(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-recent-voice-logs.ts
var list_recent_voice_logs_default = defineTool({
  name: "list_recent_voice_logs",
  title: "List recent voice health logs",
  description: "Return the signed-in user's most recent voice health logs, including transcription, extracted health data, and agent analysis.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(10).describe("Maximum number of voice logs to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("voice_logs").select("id, transcription, health_data, agent_response, created_at").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { logs: data ?? [] } };
  }
});

// src/lib/mcp/tools/log-mood.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z2 } from "npm:zod@^3.25.76";
var log_mood_default = defineTool2({
  name: "log_mood",
  title: "Log a mood entry",
  description: "Record a mood entry for the signed-in user with optional stress, anxiety, energy, and sleep quality scores.",
  inputSchema: {
    mood: z2.string().min(1).describe("Short mood label, e.g. 'happy', 'anxious', 'tired'."),
    mood_score: z2.number().int().min(1).max(10).nullable().describe("Overall mood 1-10 (10 best). Null if unknown."),
    stress_level: z2.number().int().min(1).max(10).nullable().describe("Stress level 1-10. Null if unknown."),
    anxiety_level: z2.number().int().min(1).max(10).nullable().describe("Anxiety level 1-10. Null if unknown."),
    energy_level: z2.number().int().min(1).max(10).nullable().describe("Energy level 1-10. Null if unknown."),
    sleep_quality: z2.number().int().min(1).max(10).nullable().describe("Sleep quality 1-10. Null if unknown."),
    notes: z2.string().nullable().describe("Optional free-text notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("mood_entries").insert({ user_id: ctx.getUserId(), ...input }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Logged mood: ${input.mood}` }], structuredContent: { entry: data } };
  }
});

// src/lib/mcp/tools/list-recent-moods.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_recent_moods_default = defineTool3({
  name: "list_recent_moods",
  title: "List recent mood entries",
  description: "Return the signed-in user's most recent mood entries with scores and notes.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).default(10).describe("Maximum number of mood entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("mood_entries").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { entries: data ?? [] } };
  }
});

// src/lib/mcp/tools/log-symptom.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z4 } from "npm:zod@^3.25.76";
var log_symptom_default = defineTool4({
  name: "log_symptom",
  title: "Log a symptom",
  description: "Record a symptom for the signed-in user with severity, duration, body area, and notes.",
  inputSchema: {
    symptom: z4.string().min(1).describe("Name of the symptom, e.g. 'headache', 'nausea'."),
    severity: z4.enum(["mild", "moderate", "severe", "emergency"]).describe("Severity of the symptom."),
    duration: z4.string().nullable().describe("How long the symptom has lasted, e.g. '2 hours', '3 days'."),
    body_area: z4.string().nullable().describe("Body area affected, e.g. 'head', 'chest'."),
    notes: z4.string().nullable().describe("Optional free-text notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("symptoms").insert({ user_id: ctx.getUserId(), ...input }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Logged symptom: ${input.symptom} (${input.severity})` }], structuredContent: { entry: data } };
  }
});

// src/lib/mcp/tools/list-recent-symptoms.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_recent_symptoms_default = defineTool5({
  name: "list_recent_symptoms",
  title: "List recent symptoms",
  description: "Return the signed-in user's most recent symptom entries.",
  inputSchema: {
    limit: z5.number().int().min(1).max(50).default(20).describe("Maximum number of entries to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("symptoms").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { entries: data ?? [] } };
  }
});

// src/lib/mcp/tools/log-nutrition.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z6 } from "npm:zod@^3.25.76";
var log_nutrition_default = defineTool6({
  name: "log_nutrition_entry",
  title: "Log a meal or nutrition entry",
  description: "Record a meal or nutrition entry for the signed-in user.",
  inputSchema: {
    meal_type: z6.enum(["breakfast", "lunch", "dinner", "snack"]).describe("Type of meal."),
    food_items: z6.string().min(1).describe("Free-text description of what was eaten."),
    calories: z6.number().int().min(0).nullable().describe("Estimated calories, or null if unknown."),
    water_intake: z6.number().min(0).nullable().describe("Water intake in liters for this entry, or null."),
    notes: z6.string().nullable().describe("Optional free-text notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("nutrition_entries").insert({ user_id: ctx.getUserId(), ...input }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: `Logged ${input.meal_type}: ${input.food_items}` }], structuredContent: { entry: data } };
  }
});

// src/lib/mcp/tools/log-health-metrics.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.23.0";
import { z as z7 } from "npm:zod@^3.25.76";
var log_health_metrics_default = defineTool7({
  name: "log_health_metrics",
  title: "Log biometric health metrics",
  description: "Record a snapshot of biometric health metrics (heart rate, blood pressure, blood oxygen, sleep, steps, weight) for the signed-in user.",
  inputSchema: {
    heart_rate: z7.number().int().min(20).max(250).nullable().describe("Heart rate in bpm, or null."),
    blood_pressure: z7.string().nullable().describe("Blood pressure as 'systolic/diastolic', e.g. '120/80', or null."),
    blood_oxygen: z7.number().int().min(50).max(100).nullable().describe("SpO2 percentage 50-100, or null."),
    sleep_hours: z7.number().min(0).max(24).nullable().describe("Hours slept 0-24, or null."),
    steps: z7.number().int().min(0).nullable().describe("Step count, or null."),
    weight: z7.number().min(0).nullable().describe("Weight in kilograms, or null.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("health_metrics").insert({ user_id: ctx.getUserId(), ...input }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: "Logged health metrics." }], structuredContent: { entry: data } };
  }
});

// src/lib/mcp/tools/get-profile.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.23.0";
var get_profile_default = defineTool8({
  name: "get_profile",
  title: "Get my FitMind Care profile",
  description: "Return the signed-in user's FitMind Care profile (name, id).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    const { data, error } = await sb(ctx).from("profiles").select("id, first_name, last_name, created_at").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return { content: [{ type: "text", text: JSON.stringify(data, null, 2) }], structuredContent: { profile: data, email: ctx.getUserEmail() } };
  }
});

// src/lib/mcp/index.ts
var projectRef = "sxbxjqxcdnhfbwaoaatt";
var mcp_default = defineMcp({
  name: "fitmind-care-mcp",
  title: "AI FitMind Care",
  version: "0.1.0",
  instructions: "Tools for AI FitMind Care \u2014 a voice-enabled preventive health and mental wellness companion. Use these tools to read and record the signed-in user's health data: voice logs, mood entries, symptoms, nutrition, and biometric metrics. All operations are scoped to the authenticated user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_profile_default,
    list_recent_voice_logs_default,
    log_mood_default,
    list_recent_moods_default,
    log_symptom_default,
    list_recent_symptoms_default,
    log_nutrition_default,
    log_health_metrics_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
